import type { CancerDecisionOs } from "@/lib/os/types";
import {
  BREAST_CARE_TEAM_SLUG,
  BREAST_GENETICS_SLUG,
  BREAST_METASTATIC_SLUG,
  BREAST_NEWLY_DIAGNOSED_SLUG,
  BREAST_CLINICAL_TRIAL_SLUG,
  BREAST_FOLLOW_UP_SLUG,
  BREAST_GLOBAL_CARE_SLUG,
  BREAST_PRACTICAL_FIT_SLUG,
  BREAST_QOL_SLUG,
  BREAST_RECURRENCE_SLUG,
  BREAST_RADIATION_SLUG,
  BREAST_RECONSTRUCTION_SLUG,
  BREAST_SECOND_OPINION_SLUG,
  BREAST_SEQUENCING_SLUG,
  BREAST_SUBTYPE_SLUG,
  BREAST_SURGERY_SLUG,
  BREAST_TREATMENT_COMPARE_SLUG,
} from "@/lib/content/breast-entry-slugs";

/**
 * Breast Cancer Decision OS — P0/P1 + P2 (QoL, Practical Fit, Trial, Follow-up, Global care).
 * Clinical spine: Diagnosis → Subtype → Stage context → Surgery/local → Systemic sequencing.
 */
export const BREAST_CANCER_DECISION_OS: CancerDecisionOs = {
  cancer_slug: "breast-cancer",
  title: "Breast Cancer Decision Map",
  intro:
    "A branching journey from newly diagnosed to the next decision. Subtype and sequencing often sit before a final surgery choice. Each active node links to a decision guide — not a personal care plan.",
  moments: [
    {
      id: "node-diagnosis",
      slug: "newly-diagnosed",
      label: "1. Newly diagnosed",
      state_label: "Diagnosis confirmed",
      summary:
        "Confirm what is known, which results are outstanding (subtype, imaging, genetics when relevant), and which decisions are time-sensitive.",
      why_this_matters:
        "This matters because early sequencing mistakes are hard to undo — you need to know which results change the first plan.",
      tier: 1,
      status: "active",
      stage: "diagnosis",
      sort_order: 1,
      ai_entry_slug: BREAST_NEWLY_DIAGNOSED_SLUG,
      question_slugs: [BREAST_NEWLY_DIAGNOSED_SLUG],
      treatment_slugs: [],
      story_slugs: ["comparing-lumpectomy-and-mastectomy-priorities"],
      next_moment_ids: [
        "node-subtype",
        "node-genetics",
        "node-sequencing",
        "node-surgery",
        "node-second-opinion",
      ],
      patient_router: {
        label: "What should happen first after a breast cancer diagnosis?",
        hint: "Confirm what is known, which results are still pending, and which decisions are time-sensitive.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-subtype",
      slug: "subtype-testing",
      label: "2. Confirm subtype & biology",
      state_label: "Subtype / receptor testing",
      summary:
        "Make sure receptor, HER2, and related biology results are complete enough to shape first-line choices — or decide when waiting is not safe.",
      why_this_matters:
        "This matters because subtype often changes which systemic options and sequencing make sense.",
      tier: 1,
      status: "active",
      stage: "testing",
      sort_order: 2,
      ai_entry_slug: BREAST_SUBTYPE_SLUG,
      question_slugs: [BREAST_SUBTYPE_SLUG],
      treatment_slugs: [],
      story_slugs: [],
      next_moment_ids: [
        "node-genetics",
        "node-sequencing",
        "node-compare",
        "node-surgery",
        "node-second-opinion",
      ],
      patient_router: {
        label: "Do I need subtype results before choosing treatment?",
        hint: "Receptor / HER2 / genomic results — and whether waiting changes the first plan.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-sequencing",
      slug: "treatment-sequencing",
      label: "3. Treatment before or after surgery?",
      state_label: "Neoadjuvant vs adjuvant",
      summary:
        "Decide whether systemic therapy should start before surgery (neoadjuvant) or after — a breast-distinctive fork.",
      why_this_matters:
        "This matters because sequencing can affect surgery options, response assessment, and what information you need first.",
      tier: 1,
      status: "active",
      stage: "treatment",
      sort_order: 3,
      ai_entry_slug: BREAST_SEQUENCING_SLUG,
      question_slugs: [BREAST_SEQUENCING_SLUG],
      treatment_slugs: [],
      story_slugs: [],
      next_moment_ids: ["node-surgery", "node-compare", "node-second-opinion"],
      patient_router: {
        label: "Should treatment start before or after surgery?",
        hint: "Neoadjuvant versus adjuvant — a key fork before locking the local plan.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-surgery",
      slug: "surgery-decision",
      label: "4. Lumpectomy vs mastectomy",
      state_label: "Surgery choice",
      summary:
        "Compare breast-conserving surgery and mastectomy when both may be reasonable — including genetics and reconstruction timing as hang-card context.",
      why_this_matters:
        "This matters because two oncologically sound options can still feel very different personally.",
      tier: 1,
      status: "active",
      stage: "treatment",
      sort_order: 4,
      ai_entry_slug: BREAST_SURGERY_SLUG,
      question_slugs: [BREAST_SURGERY_SLUG],
      treatment_slugs: ["surgery"],
      story_slugs: ["comparing-lumpectomy-and-mastectomy-priorities"],
      next_moment_ids: [
        "node-genetics",
        "node-radiation",
        "node-reconstruction",
        "node-compare",
        "node-second-opinion",
      ],
      patient_router: {
        label: "How do I choose between lumpectomy and mastectomy?",
        hint: "Compare two surgery paths — including what genetics and reconstruction may change.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-second-opinion",
      slug: "second-opinion",
      label: "5. Second opinion",
      state_label: "Another review",
      summary:
        "Decide whether another expert review helps before surgery or systemic therapy.",
      why_this_matters:
        "This matters when the plan feels irreversible, recommendations conflict, or you want more confidence.",
      tier: 1,
      status: "active",
      stage: "second_opinion",
      sort_order: 5,
      ai_entry_slug: BREAST_SECOND_OPINION_SLUG,
      question_slugs: [BREAST_SECOND_OPINION_SLUG],
      treatment_slugs: [],
      story_slugs: [],
      next_moment_ids: [
        "node-care-team",
        "node-surgery",
        "node-compare",
        "node-sequencing",
      ],
      patient_router: {
        label:
          "Should I get a second opinion before surgery or systemic therapy?",
        hint: "When another review may help before an irreversible step.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-compare",
      slug: "treatment-comparison",
      label: "6. Systemic therapy options",
      state_label: "Systemic options by subtype",
      summary:
        "Compare systemic options for your subtype (HR+ / HER2+ / TNBC) — goals, sequencing, and trade-offs — not a flat drug menu.",
      why_this_matters:
        "This matters because subtype forks the conversation more sharply than a single “best chemo” list.",
      tier: 1,
      status: "active",
      stage: "treatment",
      sort_order: 6,
      ai_entry_slug: BREAST_TREATMENT_COMPARE_SLUG,
      question_slugs: [BREAST_TREATMENT_COMPARE_SLUG],
      treatment_slugs: ["chemotherapy", "targeted-therapy", "immunotherapy"],
      story_slugs: [],
      next_moment_ids: ["node-second-opinion"],
      facets: [
        "Endocrine therapy",
        "Chemotherapy",
        "HER2-targeted therapy",
        "Immunotherapy (selected TNBC)",
        "Neoadjuvant vs adjuvant timing",
      ],
      patient_router: {
        label:
          "How do I choose systemic therapy for my breast cancer subtype?",
        hint: "Compare HR+ / HER2+ / TNBC option families — not a drug ranking.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-genetics",
      slug: "genetics",
      label: "Genetic counseling / BRCA",
      state_label: "Germline genetics",
      summary:
        "Whether genetic counseling and BRCA-class testing should happen before surgery — and how results may change the operation.",
      why_this_matters:
        "Germline risk is not the same as tumor subtype — it can change surgery and family implications.",
      tier: 1,
      status: "active",
      stage: "testing",
      sort_order: 7,
      ai_entry_slug: BREAST_GENETICS_SLUG,
      question_slugs: [BREAST_GENETICS_SLUG],
      treatment_slugs: [],
      story_slugs: [],
      next_moment_ids: ["node-surgery", "node-second-opinion"],
      patient_router: {
        label:
          "Do I need genetic counseling before breast cancer surgery?",
        hint: "Inherited risk (BRCA-class) vs surgery timing — not the same as tumor subtype.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-reconstruction",
      slug: "reconstruction",
      label: "Reconstruction timing",
      state_label: "Reconstruction",
      summary:
        "How reconstruction timing and choices fit into the cancer decision.",
      why_this_matters:
        "Reconstruction is part of the surgery conversation for many people — not a separate afterthought only.",
      tier: 1,
      status: "active",
      stage: "treatment",
      sort_order: 8,
      ai_entry_slug: BREAST_RECONSTRUCTION_SLUG,
      question_slugs: [BREAST_RECONSTRUCTION_SLUG],
      treatment_slugs: ["surgery"],
      story_slugs: [],
      next_moment_ids: [
        "node-surgery",
        "node-radiation",
        "node-second-opinion",
      ],
      patient_router: {
        label:
          "How do reconstruction timing and choices fit into my cancer decision?",
        hint: "Immediate vs delayed vs none — inside mastectomy, radiation, and recovery.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-radiation",
      slug: "radiation-decision",
      label: "Radiation decisions",
      state_label: "Radiation",
      summary:
        "How radiation decisions factor into breast-conserving treatment, mastectomy plans, and reconstruction timing.",
      why_this_matters:
        "Radiation often follows lumpectomy and is sometimes needed after mastectomy — assumptions can tip the whole local plan.",
      tier: 1,
      status: "active",
      stage: "treatment",
      sort_order: 9,
      ai_entry_slug: BREAST_RADIATION_SLUG,
      question_slugs: [BREAST_RADIATION_SLUG],
      treatment_slugs: [],
      story_slugs: [],
      next_moment_ids: [
        "node-surgery",
        "node-reconstruction",
        "node-second-opinion",
      ],
      patient_router: {
        label:
          "How should radiation factor into my breast cancer treatment?",
        hint: "After lumpectomy or mastectomy — schedule, side effects, and reconstruction impact.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-care-team",
      slug: "care-center-expertise",
      label: "Care team / center",
      state_label: "Care team",
      summary:
        "How to choose a breast cancer care team or center — expertise, coordination, and hybrid setups.",
      why_this_matters:
        "Fragmented teams can conflict on surgery, sequencing, radiation, and reconstruction even when each specialist is skilled.",
      tier: 1,
      status: "active",
      stage: "second_opinion",
      sort_order: 12,
      ai_entry_slug: BREAST_CARE_TEAM_SLUG,
      question_slugs: [BREAST_CARE_TEAM_SLUG],
      treatment_slugs: [],
      story_slugs: [],
      next_moment_ids: ["node-second-opinion", "node-surgery", "node-compare"],
      patient_router: {
        label: "How do I choose a breast cancer care team or center?",
        hint: "Expertise and coordination — not hospital fame. Hybrid care is often workable.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-stage-iv",
      slug: "stage-iv-options",
      label: "Metastatic / stage IV options",
      state_label: "Metastatic disease",
      summary:
        "Options when breast cancer is metastatic or stage IV — control, symptoms, and quality of life.",
      why_this_matters:
        "Goals and trade-offs shift when disease is advanced — patients need a clear decision path that is not “nothing can be done.”",
      tier: 1,
      status: "active",
      stage: "treatment",
      sort_order: 13,
      ai_entry_slug: BREAST_METASTATIC_SLUG,
      question_slugs: [BREAST_METASTATIC_SLUG],
      treatment_slugs: [],
      story_slugs: [],
      next_moment_ids: ["node-compare", "node-second-opinion", "node-care-team"],
      patient_router: {
        label: "What are my options for metastatic / Stage IV breast cancer?",
        hint: "Active treatment, control, and quality of life — shaped by subtype and goals.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-recurrence",
      slug: "recurrence",
      label: "If breast cancer comes back",
      state_label: "Recurrence",
      summary:
        "What to sort out if breast cancer returns after treatment — a new decision point, not an auto-replay.",
      why_this_matters:
        "Recurrence is a new decision point — location, prior therapy, and re-testing shape the next options.",
      tier: 1,
      status: "active",
      stage: "recurrence",
      sort_order: 14,
      ai_entry_slug: BREAST_RECURRENCE_SLUG,
      question_slugs: [BREAST_RECURRENCE_SLUG],
      treatment_slugs: [],
      story_slugs: [],
      next_moment_ids: [
        "node-stage-iv",
        "node-compare",
        "node-second-opinion",
        "node-care-team",
      ],
      patient_router: {
        label: "What should I sort out if breast cancer comes back?",
        hint: "A new decision point — location, prior therapy, and whether subtype should be re-checked.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-qol",
      slug: "quality-of-life",
      label: "Quality of life / personal goals",
      state_label: "Personal goals",
      summary:
        "Bring personal goals, daily life, and priorities into breast cancer treatment conversations.",
      why_this_matters:
        "Cancer decisions are about your life, not only your cancer — priorities make trade-offs clearer.",
      tier: 2,
      status: "active",
      stage: "supportive",
      sort_order: 15,
      optional: true,
      ai_entry_slug: BREAST_QOL_SLUG,
      question_slugs: [BREAST_QOL_SLUG],
      treatment_slugs: [],
      story_slugs: [],
      next_moment_ids: [
        "node-compare",
        "node-reconstruction",
        "node-radiation",
        "node-second-opinion",
      ],
      patient_router: {
        label: "How should quality of life factor into my breast cancer plan?",
        hint: "Support cancer goals and the daily life you need to protect — not treatment vs living.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-costs",
      slug: "cost-logistics",
      label: "Practical fit (cost & logistics pointer)",
      state_label: "Practical fit",
      summary:
        "Pointer into Care Team, Systemic options, and Quality of Life — whether a plan can work with cost, travel, time, and support.",
      why_this_matters:
        "Practical factors belong in the conversation. Open the matching decision page rather than treating logistics as a separate encyclopedia.",
      tier: 2,
      status: "active",
      stage: "practical",
      sort_order: 16,
      optional: true,
      ai_entry_slug: BREAST_PRACTICAL_FIT_SLUG,
      question_slugs: [BREAST_PRACTICAL_FIT_SLUG],
      treatment_slugs: [],
      story_slugs: [],
      next_moment_ids: [
        "node-care-team",
        "node-compare",
        "node-qol",
        "node-second-opinion",
      ],
      patient_router: {
        label: "Can this breast cancer plan work with my real life?",
        hint: "Practical fit — then Care Team, Systemic options, or Quality of Life.",
        nextStep: "See where to go next",
      },
    },
    {
      id: "node-clinical-trial",
      slug: "clinical-trial",
      label: "Clinical trial decision",
      state_label: "Clinical trial decision",
      summary:
        "Decide whether a clinical trial should be part of your discussion — compared with other options, not as a last resort.",
      why_this_matters:
        "Trials are a decision option at multiple points — evaluate purpose, evidence, risks, subtype fit, and practical burden.",
      tier: 1,
      status: "active",
      stage: "treatment",
      sort_order: 17,
      ai_entry_slug: BREAST_CLINICAL_TRIAL_SLUG,
      question_slugs: [BREAST_CLINICAL_TRIAL_SLUG],
      treatment_slugs: [],
      story_slugs: [],
      next_moment_ids: [
        "node-compare",
        "node-second-opinion",
        "node-care-team",
        "node-stage-iv",
      ],
      patient_router: {
        label: "Should I consider a clinical trial for breast cancer?",
        hint: "Another option to evaluate — not automatically better, not only last resort.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-follow-up",
      slug: "follow-up-monitoring",
      label: "Long-term monitoring & follow-up",
      state_label: "Follow-up monitoring",
      summary:
        "After active treatment, clarify what to monitor, when to contact the team, and how ongoing medicines fit.",
      why_this_matters:
        "The end of treatment is not the end of care — patients need a clear plan for visits, symptoms, late effects, and life after cancer.",
      tier: 2,
      status: "active",
      stage: "supportive",
      sort_order: 18,
      optional: true,
      ai_entry_slug: BREAST_FOLLOW_UP_SLUG,
      question_slugs: [BREAST_FOLLOW_UP_SLUG],
      treatment_slugs: [],
      story_slugs: [],
      next_moment_ids: [
        "node-recurrence",
        "node-qol",
        "node-second-opinion",
      ],
      patient_router: {
        label: "How do I monitor my health after breast cancer treatment?",
        hint: "Follow-up plans, symptoms to report, ongoing medicines, and life after treatment.",
        nextStep: "Start here",
      },
    },
    {
      id: "node-global",
      slug: "global-care",
      label: "Local vs international branch",
      state_label: "International option",
      summary:
        "Only explore cross-border care when a specific capability, trial, or specialty review is missing locally.",
      why_this_matters:
        "This matters only when a specific capability is missing locally — not as a default upgrade.",
      tier: 2,
      status: "active",
      stage: "global",
      sort_order: 19,
      optional: true,
      ai_entry_slug: BREAST_GLOBAL_CARE_SLUG,
      question_slugs: [BREAST_GLOBAL_CARE_SLUG],
      treatment_slugs: [],
      story_slugs: [],
      next_moment_ids: [
        "node-care-team",
        "node-second-opinion",
        "node-clinical-trial",
        "node-costs",
      ],
      patient_router: {
        label: "When should I consider breast cancer care abroad?",
        hint: "Explore only when a capability gap is real — name it in one sentence.",
        nextStep: "Start here",
      },
    },
  ],
};
